version: '3.8'

services:
  jupyter:
    image: nvcr.io/nvidia/pytorch:24.05-py3
    container_name: jupyter_notebook
    command: jupyter notebook --allow-root --ip=0.0.0.0 --no-browser --notebook-dir=/workspace
    ports:
      - "2223:22"
      - "8888:8888"
    volumes:
      - .:/workspace
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        limits:
          memory: -1
        reservations:
          memory: 67108864
    ipc: host
    ulimits:
      memlock:
        name: memlock
        soft: -1
        hard: -1
      stack:
        name: stack
        soft: 67108864
        hard: 67108864
